### ISSUE TITLE
Update to work with upcoming express-stormpath@3.0

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-sdk-angularjs#105]
With these changes I think we should move this library to 1.0 - ping @timothyej 
### Todo
- [x] Add X-Stormpath-Agent header (#106)
- [x] Implement the login view model (#108)
- [x] Implement the registration view model (#109)
- [x] Implement the new JSON error responses (#110)
- [x] Change logout to use POST request (#116)

**Comment by timothyej** [comment]
Yes, sounds good to me :+1:

I will start working on the view models.
